In [1]:
#from skimage import io
import glob
import numpy as np
import os
import cv2
import PIL
from PIL import Image
import skimage
from skimage import io
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
#from sklearn.metrics import silhouette_score


In [2]:
labels_npy=np.loadtxt("C:\\Users\\karm_ch\\Documents\\autocoast\\data\\s2raw\\selected_samples\\labels_np_correct.txt")

In [4]:
print(np.unique(labels_npy), labels_npy.shape) 

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] (193, 260100)


In [6]:
kmeanslabels_npy = np.loadtxt("C:\\Users\karm_ch\\Documents\\autocoast\\data\\s2raw\\data_np\\kmeanslabels.txt")


In [5]:
gmlabels_npy= np.loadtxt("C:\\Users\karm_ch\\Documents\\autocoast\\code\\gmlabels.txt")

In [6]:
print(np.unique(gmlabels_npy), gmlabels_npy.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] (5202000,)


In [6]:
gmlabels_npy.shape

(5202000,)

In [12]:
kmeanslabels_npy= kmeanslabels_npy.reshape(labels_npy.shape[0], int(kmeanslabels_npy.shape[0] / labels_npy.shape[0] ))

In [11]:
print(labels_npy.shape,kmeanslabels_npy.shape)

(193, 260100) (50199300,)


In [ ]:
#flattten the arrays for having pixel-level single feature arrays 


In [7]:
# do a pixel-level water- nonwater classification 

#X = kmeanslabels_npy#.reshape(kmeanslabels_npy.shape[0] * kmeanslabels_npy.shape[1])

X = gmlabels_npy
Y= labels_npy.reshape(labels_npy.shape[0] * labels_npy.shape[1])

Y=Y[0:X.shape[0]]
print(X.shape, Y.shape)

(5202000,) (5202000,)


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=42)
print(X_train.shape)
print(f'Training set size - X_train: {X_train.shape}, Y_train: {Y_train.shape}')
print(f'Test set size - X_test: {X_test.shape}, Y_train: {Y_test.shape}')

(3901500,)
Training set size - X_train: (3901500,), Y_train: (3901500,)
Test set size - X_test: (1300500,), Y_train: (1300500,)


In [9]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(X_train.reshape(-1, 1), Y_train)
clf.score(X_test.reshape(-1, 1), Y_test)

0.5953640907343329

In [10]:
Y_pred=clf.predict(X_test.reshape(-1,1))

In [11]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(Y_test, Y_pred)
print(conf_mat)

[[226526  34077 140499      0      0      0      0      0      0     98
       0]
 [ 20123 262753   3136      0      0      0      0      0      0      0
       0]
 [ 22659   1540 283267      0      0      0      0      0      0      0
       0]
 [ 22749      7   2220      0      0      0      0      0      0      0
       0]
 [ 15330   7741   8328      0      0      0      0      0      0      0
       0]
 [ 19470    450   3472      0      0      0      0      0      0      0
       0]
 [122997   1512  18526      0      0      0      0      0      0      0
       0]
 [ 47548    404   7366      0      0      0      0      0      0      5
       0]
 [ 15687   1315    372      0      0      0      0      0      0      0
       0]
 [   549      0      0      0      0      0      0      0      0   1725
       0]
 [  7993     52      4      0      0      0      0      0      0      0
       0]]


In [12]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

C:\Users\karm_ch\AppData\Local\Continuum\anaconda3\envs\gdal_env\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\karm_ch\AppData\Local\Continuum\anaconda3\envs\gdal_env\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

         0.0       0.43      0.56      0.49    401200
         1.0       0.85      0.92      0.88    286012
         2.0       0.61      0.92      0.73    307466
         3.0       0.00      0.00      0.00     24976
         4.0       0.00      0.00      0.00     31399
         5.0       0.00      0.00      0.00     23392
         6.0       0.00      0.00      0.00    143035
         7.0       0.00      0.00      0.00     55323
         8.0       0.00      0.00      0.00     17374
         9.0       0.94      0.76      0.84      2274
        10.0       0.00      0.00      0.00      8049

    accuracy                           0.60   1300500
   macro avg       0.26      0.29      0.27   1300500
weighted avg       0.47      0.60      0.52   1300500



C:\Users\karm_ch\AppData\Local\Continuum\anaconda3\envs\gdal_env\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
print(X.shape, Y.shape)

(5202000,) (5202000,)


In [13]:
Y_binary = (Y==1)

In [14]:
Y_binary

array([False, False, False, ..., False, False, False])

In [15]:
Y_binary=Y_binary.astype(int)

In [16]:
np.count_nonzero(Y_binary)

1142827

In [17]:
np.count_nonzero(Y_binary)/ Y_binary.shape[0] # 26.6 % of all samples are water, dataset is highly imbalanced

0.21968992695117262

You want to change your evaluation metric from accuracy to something else, such as F1 score or precision and recall in this case.

http://www.svds.com/learning-imbalanced-classes/

# Malai Kofta

In [18]:
print("malai kofta")

malai kofta


In [19]:
for i in range(10): 
    print(str(i) + "my alu paratha")

0my alu paratha
1my alu paratha
2my alu paratha
3my alu paratha
4my alu paratha
5my alu paratha
6my alu paratha
7my alu paratha
8my alu paratha
9my alu paratha


# That said, here is a rough outline of useful approaches. These are listed approximately in order of effort:

Do nothing. Sometimes you get lucky and nothing needs to be done. You can train on the so-called natural (or stratified) distribution and sometimes it works without need for modification.
Balance the training set in some way:
Oversample the minority class.
Undersample the majority class.
Synthesize new minority classes.
Throw away minority examples and switch to an anomaly detection framework.
At the algorithm level, or after it:
Adjust the class weight (misclassification costs).
Adjust the decision threshold.
Modify an existing algorithm to be more sensitive to rare classes.
Construct an entirely new algorithm to perform well on imbalanced data.

Let's undersample the majority class

In [20]:
X_bin=[]
Y_bin=[]
max_wanted_number_of_water_pixels= X.shape[0]/2
max_wanted_number_of_nonwater_pixels= X.shape[0]/2

count_0=0 # count of non-water pixels
count_1=0 # count of water pixels

for i in range(X.shape[0]): # non-water
    if (Y[i] > 1 and count_0 <= max_wanted_number_of_nonwater_pixels): # labels that are neither water not no-data (0)
        X_bin.append(X[i])
        Y_bin.append(int(1))
        count_0+=1
    elif (Y[i] == 1 and count_1 <= max_wanted_number_of_water_pixels): # labels that are water (1)
        X_bin.append(X[i])
        Y_bin.append(int(0))
        count_1+=1
    else:
        continue 

In [21]:
X_bin=np.array(X_bin)
Y_bin=np.array(Y_bin)
print(X_bin.shape,Y_bin.shape )

(3598846,) (3598846,)


In [22]:
#save to disk
np.savetxt('train_test_X_gm.txt', X, fmt='%d')
np.savetxt('train_test_Y.txt', Y, fmt='%d')

In [23]:
np.count_nonzero(Y_bin)

2456019

In [24]:
Y_bin.shape[0]/(Y_bin.shape[0]- np.count_nonzero(Y_bin))

3.149073306808467

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


X_train, X_test, Y_train, Y_test = train_test_split(X_bin, Y_bin, test_size=0.25, random_state=42)
print(X_train.shape)
print(f'Training set size - X_train: {X_train.shape}, Y_train: {Y_train.shape}')
print(f'Test set size - X_test: {X_test.shape}, Y_train: {Y_test.shape}')

clf = RandomForestClassifier()
clf.fit(X_train.reshape(-1, 1), Y_train)
clf.score(X_test.reshape(-1, 1), Y_test)

(2699134,)
Training set size - X_train: (2699134,), Y_train: (2699134,)
Test set size - X_test: (899712,), Y_train: (899712,)


0.9613576344430218

In [26]:
Y_pred=clf.predict(X_test.reshape(-1,1))

In [27]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94    285392
           1       0.98      0.96      0.97    614320

    accuracy                           0.96    899712
   macro avg       0.95      0.96      0.96    899712
weighted avg       0.96      0.96      0.96    899712



In [30]:
import joblib
joblib.dump(clf,"C:\\Users\\karm_ch\\Documents\\autocoast\\tool_data\\models\\autocoast_binary_random_forest.jl")

['C:\\Users\\karm_ch\\Documents\\autocoast\\tool_data\\models\\autocoast_binary_random_forest.jl']

# Uncertainty in prediction

A RandomForestClassifier is a collection of DecisionTreeClassifier's. No matter how big your training set, a decision tree simply returns: a decision. One class has probability 1, the other classes have probability 0.

The RandomForest simply votes among the results. predict_proba() returns the number of votes for each class (each tree in the forest makes its own decision and chooses exactly one class), divided by the number of trees in the forest. Hence, your precision is exactly 1/n_estimators. Want more "precision"? Add more estimators. If you want to see variation at the 5th digit, you will need 10**5 = 100,000 estimators, which is excessive. You normally don't want more than 100 estimators, and often not that many.

In [ ]:
# the patches are 510 x 510 pixels at the moment, too big to assign any semantic labels 
# Let's tile them into 10 x 10 pixels to assign labels 

#then assign these tiled patches some class based on what they contain. 

                    #if 100% of the pixels are water - labels 0 
    
                    #if 100% are non-water - label 1
        
                    # else label 2 - these are coasts 

# correlation between adjacent pixels 

In [ ]:
# tile the patches 
lables_npy_tiles=np.zeros((labels_npy.shape[0] * 51 * 51 ),( 10 * 10 ))

for i in range(labels_npy.shape[0]): 
    patch= labels_npy[i]
    for j in range(patch[j]): 
        

In [ ]:
# read the labels 

#rewrite the labels : if 100% of the pixels are water - labels 0 
                    #if 100% are non-water - label 1
                    # else label 2 # coasts 
        
water_samples=[]
land_samples=[]
coast_samples=[]

for i in range(data.shape[0]): # for each patch
    
    sample= data[i]
    count_water=0
    count_land=0
    total_number_of_pixels = sample.shape[0]
    
    for j in range(sample.shape[0]): # check pixels inside each patch
        
        if (label ==) : 
            count_water++
        elif (label == ): 
            count_land++
        else: 
            count_coast++
    
    if (count_water == total_number_of pi